### PR TITLE
The test that loads the file works! (and also his three test friends)

### PR DESCRIPTION
**Pull request by rocboronat**
Now, the project can read the .dat file. BTW, I didn't deeped into the implementation, so... time to review!

### CODE REVIEW

**Comment by ed-george** [comment]
Nice @rocboronat , that works perfectly - Also managed to fix my IDE to run it as well.

**Comment by rocboronat** [comment]
Great! I'm going to remove my own fork of your project, and working on the Fewlaps one again :·)

Waiting that PR! :·P

**Comment by ed-george** [comment]
Awesome, yeah will make it later today - I think my work computer is using the wrong git config credentials for my commits

**Comment by rocboronat** [comment]
No hurry! We're doing it for love :·)

**Pull request merged**
